spring:
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
logging:
  level:
    org.springframework.security: trace
    xyz.catuns: debug
    org:
      slf4j: debug


