spring:
  application:
    name: recruiter-to-vendor
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:rtv_app}
    username: ${DATABASE_USER:default}
    password: ${DATABASE_PASSWORD:password}
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  security:
    user:
      name: default
      password: some-password
